version: '3.9'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: midgard
    volumes:
      - db_data:/var/lib/postgresql/data
  midgard:
    build: .
    environment:
      DB_URI: postgresql+asyncpg://user:password@db:5432/midgard
      DB_CACHE_TTL: ${DB_CACHE_TTL}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_DEFAULT_GUILD_ID: ${DISCORD_DEFAULT_GUILD_ID}
      DISCORD_INVITE_URL: ${DISCORD_INVITE_URL}
      OS_PROJECT_DOMAIN_NAME: ${OS_PROJECT_DOMAIN_NAME}
      OS_USER_DOMAIN_NAME: ${OS_USER_DOMAIN_NAME}
      OS_PROJECT_NAME: ${OS_PROJECT_NAME}
      OS_TENANT_NAME: ${OS_TENANT_NAME}
      OS_USERNAME: ${OS_USERNAME}
      OS_PASSWORD: ${OS_PASSWORD}
      OS_AUTH_URL: ${OS_AUTH_URL}
      OS_INTERFACE: ${OS_INTERFACE}
      OS_ENDPOINT_TYPE: ${OS_ENDPOINT_TYPE}
      OS_IDENTITY_API_VERSION: ${OS_IDENTITY_API_VERSION}
      OS_REGION_NAME: ${OS_REGION_NAME}
      OS_AUTH_PLUGIN: ${OS_AUTH_PLUGIN}
      OS_DEFAULT_GUILD_PREFIX: ${OS_DEFAULT_GUILD_PREFIX}
      CF_API_KEY: ${CF_API_KEY}
      CF_ACCOUNT_ID: ${CF_ACCOUNT_ID}
      CF_TUNNEL_ID: ${CF_TUNNEL_ID}
      CF_DOMAIN: ${CF_DOMAIN}
      CF_ZONE_ID: ${CF_ZONE_ID}
    depends_on:
      - db
    command: midgard-bot
volumes:
  db_data:
