name: "Run all tests"

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install pre-commit
      run: |
        set -xe
        python -m pip install --upgrade pre-commit
        pre-commit install
    - name: Run pre-commit
      run: |
        set -xe
        python -m pre_commit
  tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    uses: ./.github/workflows/pytest.yml
    with:
      python-version: ${{ matrix.python-version}}
  check:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Coverage.py
      run: |
        set -xe
        python -m pip install --upgrade coverage[toml]
    - name: Download coverage data for all test runs
      uses: actions/download-artifact@v3
      with:
        name: coverage-per-interpreter
    - name: Combine coverage data and create report
      run: |
        coverage combine
        coverage xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        fail_ci_if_error: true
