name: "Run all tests"

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    uses: ./.github/workflows/run-pytest.yml
    with:
      python-version: ${{ matrix.python-version}}
